#!/usr/bin/env bash
# Generates stone/<extension>/carrier-bsp/ for every module variant, from the
# pinned Avocado jetson-orin-nx flash BSP plus ARK's JAJ sources (upstream.env).
#
# Per variant it produces:
#   - the kernel DTB: Avocado's stock DTB for that SKU, with ARK's carrier
#     fragment, model string and dual-IMX219 camera overlay applied
#   - the MB1 pinmux/GPIO BCT: ARK's files, renamed with an -ark-jaj suffix
#   - the MB2 misc BCT: stock, with the carrier EEPROM read disabled (the JAJ
#     has none at the address the stock file reads, same change ARK makes)
#   - ark-jaj-boot-order.dtbo: ARK's UEFI boot order overlay
#   - carrier.env: points the flash at all of the above, and pins the SKU
#
# The output is committed. The stone/ tree of a fetched extension is copied
# as-is, so it can't be generated by a build step on the consumer's side.
#
# Usage:
#   scripts/build-carrier-bsp.sh            regenerate stone/
#   scripts/build-carrier-bsp.sh --check    regenerate into a temp dir and fail
#                                           if it differs from the committed stone/
#   scripts/build-carrier-bsp.sh --drift    fail if the feed's newest snapshot
#                                           ships a different flash BSP than the pin
#
# Needs: dtc, fdtoverlay, fdtget, a C preprocessor (cc), bsdtar, curl, perl,
# sha256sum or shasum. On Debian/Ubuntu: device-tree-compiler cpp
# libarchive-tools curl. On macOS: brew install dtc.
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT=$PWD
. ./upstream.env

die() {
	echo "build-carrier-bsp: $*" >&2
	exit 1
}
info() {
	echo "build-carrier-bsp: $*"
}

MODE=build
case "${1:-}" in
"") ;;
--check) MODE=check ;;
--drift) MODE=drift ;;
*) die "unknown argument '$1' (see the header of this script)" ;;
esac

for tool in curl perl gzip; do
	command -v "$tool" >/dev/null || die "$tool not found"
done
if [ "$MODE" != drift ]; then
	for tool in dtc fdtoverlay fdtget bsdtar "${CC:-cc}"; do
		command -v "$tool" >/dev/null || die "$tool not found"
	done
fi
if command -v sha256sum >/dev/null; then
	sha256() { sha256sum "$1" | cut -d' ' -f1; }
elif command -v shasum >/dev/null; then
	sha256() { shasum -a 256 "$1" | cut -d' ' -f1; }
else
	die "sha256sum or shasum not found"
fi

FEED="$AVOCADO_REPO_URL/$AVOCADO_RELEASE/$AVOCADO_CHANNEL"

# Newest avocado-img-bootfiles in a snapshot's primary.xml, as "<sha256>".
bootfiles_in_snapshot() {
	local base="$FEED/snapshots/$1/target/$AVOCADO_TARGET" primary
	primary=$(curl -fsSL "$base/repodata/repomd.xml" | grep -o 'repodata/[^"]*-primary\.xml\.gz' | head -n 1) \
		|| die "no repodata for snapshot $1 at $base"
	curl -fsSL "$base/$primary" | gzip -dc | perl -0777 -ne '
		my ($best, $bestrel);
		while (/<package type="rpm">(.*?)<\/package>/sg) {
			my $p = $1;
			next unless $p =~ m{<name>avocado-img-bootfiles</name>};
			my ($rel) = $p =~ m{<version [^>]*rel="r0\.(\d+)"};
			my ($sum) = $p =~ m{<checksum type="sha256"[^>]*>(\w+)<};
			($best, $bestrel) = ($sum, $rel) if !defined $bestrel || $rel > $bestrel;
		}
		print "$best\n" if defined $best;'
}

if [ "$MODE" = drift ]; then
	latest=$(curl -fsSL "$FEED/target/$AVOCADO_TARGET/snapshots-latest.json" | perl -ne 'print $1 if /"id":\s*"?(\d+)/')
	[ -n "$latest" ] || die "could not read the latest snapshot id"
	sum=$(bootfiles_in_snapshot "$latest")
	[ -n "$sum" ] || die "snapshot $latest has no avocado-img-bootfiles"
	if [ "$sum" != "$BOOTFILES_SHA256" ]; then
		die "snapshot $latest ships a different flash BSP ($sum) than the pinned one (snapshot $AVOCADO_SNAPSHOT, $BOOTFILES_SHA256). Set AVOCADO_SNAPSHOT=$latest and BOOTFILES_SHA256=$sum in upstream.env, rerun this script and review the DTB diff."
	fi
	info "snapshot $latest still ships the pinned flash BSP"
	exit 0
fi

# ---------------------------------------------------------------------------
# Fetch the pinned flash BSP (content-addressed, so the hash is the name).
# ---------------------------------------------------------------------------
CACHE="$ROOT/build/cache"
mkdir -p "$CACHE"
rpm="$CACHE/$BOOTFILES_SHA256.rpm"
if [ ! -f "$rpm" ] || [ "$(sha256 "$rpm")" != "$BOOTFILES_SHA256" ]; then
	info "downloading avocado-img-bootfiles ($BOOTFILES_SHA256)"
	curl -fSL "$FEED/_pkgs/${BOOTFILES_SHA256:0:2}/$BOOTFILES_SHA256.rpm" -o "$rpm.part"
	mv "$rpm.part" "$rpm"
fi
[ "$(sha256 "$rpm")" = "$BOOTFILES_SHA256" ] || die "$rpm does not match BOOTFILES_SHA256"

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT
BSP="$WORK/tegraflash-bsp"
stock_files=(
	flashvars
	.env.initrd-flash
	tegra234-p3768-0000+p3767-0000-nv-super.dtb
	tegra234-p3768-0000+p3767-0001-nv-super.dtb
	tegra234-mb2-bct-misc-p3767-0000.dts
	tegra234-mb1-bct-pinmux-p3767-dp-a03.dtsi
	tegra234-bpmp-3767-0001-3768-super.dtb
	tegra234-p3767-0001-wb0sdram-l4t.dts
	tegra234-p3767-0001-sdram-l4t.dts
	L4TConfiguration.dtbo
	L4TConfiguration-RootfsRedundancyLevelABEnable.dtbo
)
patterns=()
for f in "${stock_files[@]}"; do patterns+=("./tegraflash-bsp/$f"); done
bsdtar -xf "$rpm" -C "$WORK" "${patterns[@]}" || die "flash BSP is missing one of: ${stock_files[*]}"
for f in "${stock_files[@]}"; do
	[ -f "$BSP/$f" ] || die "flash BSP is missing $f"
done

# Keys a carrier.env may retarget must already exist, or the provision script
# only prints a WARNING and flashes the stock value.
flashvar() {
	grep -q "^$1=" "$BSP/flashvars" || die "flashvars has no $1"
	sed -n "s/^$1=\"\{0,1\}\([^\"]*\)\"\{0,1\}\$/\1/p" "$BSP/flashvars"
}
envvar() {
	grep -q "^$1=" "$BSP/.env.initrd-flash" || die ".env.initrd-flash has no $1"
}

# This repo only knows how to layer onto the SKU-0000 defaults of the
# jetson-orin-nx MACHINE. If Avocado changes those, stop and look.
[ "$(flashvar CHECK_BOARDSKU)" = 0000 ] || die "the pinned BSP no longer defaults to SKU 0000"
[ "$(flashvar PINMUX_CONFIG)" = tegra234-mb1-bct-pinmux-p3767-dp-a03.dtsi ] || die "stock PINMUX_CONFIG changed"
[ "$(flashvar MB2BCT_CFG)" = tegra234-mb2-bct-misc-p3767-0000.dts ] || die "stock MB2BCT_CFG changed"
STOCK_OVERLAYS=$(flashvar BOOTCONTROL_OVERLAYS)
[ -n "$STOCK_OVERLAYS" ] || die "stock BOOTCONTROL_OVERLAYS is empty"
for key in CHECK_BOARDID BPFDTB_FILE CHIP_SKU WB0SDRAM_BCT; do flashvar "$key" >/dev/null; done
for key in DTBFILE EMMC_BCTS; do envvar "$key"; done

cpp_dts() {
	"${CC:-cc}" -E -P -nostdinc -undef -D__DTS__ -x assembler-with-cpp \
		-I "$ROOT/src/include" -I "$ROOT/src/ark" -I "$(dirname "$1")" "$1" -o "$2"
}

# ---------------------------------------------------------------------------
# Shared outputs
# ---------------------------------------------------------------------------
SHARED="$WORK/shared"
mkdir -p "$SHARED"

cpp_dts "$ROOT/src/ark/tegra234-p3767-camera-p3768-imx219-dual.dts" "$WORK/camera.dts"
dtc -q -@ -I dts -O dtb -o "$WORK/camera.dtbo" "$WORK/camera.dts"

dtc -q -I dts -O dtb -o "$SHARED/ark-jaj-boot-order.dtbo" "$ROOT/src/ark/ark_boot_order.dts"

# Pinmux + GPIO: ARK's files, renamed so the flash log shows whose they are.
# The pinmux #includes the GPIO file by name; retarget that one line (CRLF kept).
PINMUX=tegra234-mb1-bct-pinmux-p3767-dp-a03-ark-jaj.dtsi
GPIO=tegra234-mb1-bct-gpio-p3767-dp-a03-ark-jaj.dtsi
cp "$ROOT/src/ark/tegra234-mb1-bct-gpio-p3767-dp-a03.dtsi" "$SHARED/$GPIO"
perl -pe 's{^(#include "\./)tegra234-mb1-bct-gpio-p3767-dp-a03\.dtsi(")}{$1'"$GPIO"'$2}' \
	"$ROOT/src/ark/tegra234-mb1-bct-pinmux-p3767-dp-a03.dtsi" >"$SHARED/$PINMUX"
[ "$(grep -c "#include \"./$GPIO\"" "$SHARED/$PINMUX")" -eq 1 ] || die "could not retarget the GPIO #include in ARK's pinmux"
if grep -q 'tegra234-mb1-bct-gpio-p3767-dp-a03\.dtsi' "$SHARED/$PINMUX"; then
	die "ARK's pinmux still includes the stock GPIO file"
fi

# MB2 misc: stock file with only the carrier EEPROM read disabled.
MB2=tegra234-mb2-bct-misc-p3767-0000-ark-jaj.dts
perl -pe 's{^(\s*cvb_eeprom_read_size = )<0x100>;}{$1<0x0>;}' \
	"$BSP/tegra234-mb2-bct-misc-p3767-0000.dts" >"$SHARED/$MB2"
[ "$(diff "$BSP/tegra234-mb2-bct-misc-p3767-0000.dts" "$SHARED/$MB2" | grep -c '^>')" -eq 1 ] \
	|| die "expected exactly one change (cvb_eeprom_read_size) in the stock MB2 misc BCT"

# ---------------------------------------------------------------------------
# Per variant
# ---------------------------------------------------------------------------
# name  sku   description
VARIANTS=(
	"nx16 0000 Jetson Orin NX 16GB"
	"nx8  0001 Jetson Orin NX 8GB"
)

OUT="$WORK/stone"

build_dtb() {
	local sku=$1 out=$2 model base="$BSP/tegra234-p3768-0000+p3767-$1-nv-super.dtb" d="$WORK/dtb-$1"
	mkdir -p "$d"
	model=$(sed -n "s/^$sku=//p" "$ROOT/src/ark/dtb_models.env")
	[ -n "$model" ] || die "src/ark/dtb_models.env has no model for SKU $sku"

	# Decompile, and drop __symbols__ so dtc -@ regenerates it with ARK's new
	# labels (uartb) included. The decompiled source keeps every other label.
	dtc -q -I dtb -O dts -o "$d/stock.dts" "$base"
	awk '/^\t__symbols__ \{$/ {skip = 1} skip && /^\t\};$/ {skip = 0; next} !skip' "$d/stock.dts" >"$d/base.dts"
	grep -q __symbols__ "$d/base.dts" && die "could not strip __symbols__ from $base"
	cat >"$d/jaj.dts" <<-EOF
		#include <dt-bindings/clock/tegra234-clock.h>
		#include <dt-bindings/reset/tegra234-reset.h>
		#include <dt-bindings/gpio/tegra234-gpio.h>
		#include <dt-bindings/interrupt-controller/arm-gic.h>
		#include "base.dts"
		#include "ark-JAJ-overrides.dtsi"
		/ { model = "$model Super"; };
	EOF
	cpp_dts "$d/jaj.dts" "$d/jaj.pp.dts"
	dtc -q -@ -I dts -O dtb -o "$d/jaj.dtb" "$d/jaj.pp.dts"
	fdtoverlay -i "$d/jaj.dtb" -o "$out" "$WORK/camera.dtbo"

	# Spot-check that each part of the JAJ delta landed.
	local lane gadget_phys
	expect() { # <fdtget type> <node> <property> <expected>
		local got
		got=$(fdtget -t "$1" "$out" "$2" "$3" 2>/dev/null) || die "SKU $sku: $2 $3 missing"
		[ "$got" = "$4" ] || die "SKU $sku: $2 $3 is '$got', expected '$4'"
	}
	expect s / model "$model Super"
	expect s /bus@0/serial@3110000 compatible nvidia,tegra194-hsuart
	expect s /bus@0/serial@3110000 status okay
	if fdtget "$out" /bus@0/serial@3100000 dmas >/dev/null 2>&1; then
		die "SKU $sku: UART-A still has DMA"
	fi
	expect s /bus@0/padctl@3520000/ports/usb3-2 status okay
	expect s /bus@0/usb@3550000 phy-names "usb2-0 usb3-0"
	lane=$(fdtget -tx "$out" /bus@0/padctl@3520000/pads/usb3/lanes/usb3-0 phandle)
	gadget_phys=$(fdtget -tx "$out" /bus@0/usb@3550000 phys)
	[ "${gadget_phys##* }" = "$lane" ] || die "SKU $sku: USB-C gadget isn't on the usb3-0 lane"
	expect u /bus@0/pcie@141e0000 max-link-speed 2
	expect s /bus@0/hda@3510000 status okay
	expect s /bus@0/cam_i2cmux status okay
	expect s /bus@0/cam_i2cmux/i2c@0/rbpcv2_imx219_a@10 compatible sony,imx219
	expect s /bus@0/cam_i2cmux/i2c@1/rbpcv2_imx219_c@10 compatible sony,imx219
}

for v in "${VARIANTS[@]}"; do
	read -r name sku desc <<<"$v"
	ext="avocado-bsp-ark-jaj-$name"
	slot="$OUT/$ext/carrier-bsp"
	mkdir -p "$slot"
	cp "$SHARED"/* "$slot/"

	dtb="tegra234-p3768-0000+p3767-$sku-nv-super-ark-jaj.dtb"
	build_dtb "$sku" "$slot/$dtb"

	{
		echo "# Generated by scripts/build-carrier-bsp.sh from upstream.env. Do not edit."
		echo "# Consumed by stone-provision-tegraflash.sh: CARRIER_FV_* rewrite flashvars,"
		echo "# CARRIER_ENV_* rewrite .env.initrd-flash."
		echo "CARRIER_LABEL=\"ARK Just A Jetson + $desc (P3767-$sku), bsp-ark-jaj\""
		echo
		echo "# JAJ kernel DTB (ARK carrier fragment + dual IMX219) for this SKU."
		echo "CARRIER_ENV_DTBFILE=\"$dtb\""
		echo
		echo "# ARK's MB1 pinmux/GPIO (IMU spi3, UART-A flow control, ...) and MB2 misc"
		echo "# with the carrier EEPROM read disabled."
		echo "CARRIER_FV_PINMUX_CONFIG=\"$PINMUX\""
		echo "CARRIER_FV_MB2BCT_CFG=\"$MB2\""
		echo
		echo "# ARK's UEFI boot order: NVMe before USB, new devices (PXE/HTTP boot options)"
		echo "# at the bottom. Appended so it wins over the stock L4TConfiguration."
		echo "CARRIER_FV_BOOTCONTROL_OVERLAYS=\"$STOCK_OVERLAYS,ark-jaj-boot-order.dtbo\""
		echo
		echo "# Refuse to flash any other module (tegraflash compares these to the EEPROM)."
		echo "CARRIER_FV_CHECK_BOARDID=\"3767\""
		echo "CARRIER_FV_CHECK_BOARDSKU=\"$sku\""
		if [ "$sku" = 0001 ]; then
			echo
			echo "# 8GB module: meta-tegra's p3768-0000-p3767-0001 values. The default"
			echo "# jetson-orin-nx MACHINE bakes the 16GB (SKU 0000) ones."
			echo "CARRIER_FV_BPFDTB_FILE=\"tegra234-bpmp-3767-0001-3768-super.dtb\""
			echo "CARRIER_FV_CHIP_SKU=\"00:00:00:D4\""
			echo "CARRIER_FV_WB0SDRAM_BCT=\"tegra234-p3767-0001-wb0sdram-l4t.dts\""
			echo "CARRIER_ENV_EMMC_BCTS=\"tegra234-p3767-0001-sdram-l4t.dts\""
		fi
	} >"$slot/carrier.env"

	# Every file carrier.env names must exist in the merged BSP.
	while IFS= read -r file; do
		[ -f "$slot/$file" ] || [ -f "$BSP/$file" ] || die "$ext: carrier.env references $file, which neither the slot nor the stock BSP has"
	done < <(sed -n 's/^CARRIER_[A-Z_]*="\(.*\)"$/\1/p' "$slot/carrier.env" | tr ',' '\n' | grep -E '\.(dtbo?|dtsi?|bin)$')
	info "built $ext ($desc)"
done

# ---------------------------------------------------------------------------
# Install, or compare
# ---------------------------------------------------------------------------
normalize() {
	case "$1" in
	*.dtb | *.dtbo) dtc -q -I dtb -O dts -s "$1" ;;
	*) cat "$1" ;;
	esac
}

if [ "$MODE" = check ]; then
	[ -d "$ROOT/stone" ] || die "stone/ is missing; run scripts/build-carrier-bsp.sh"
	diff <(cd "$OUT" && find . -type f | sort) <(cd "$ROOT/stone" && find . -type f | sort) \
		|| die "stone/ has a different file set than the pinned inputs produce"
	failed=0
	while IFS= read -r f; do
		# DTBs are compared decompiled: different dtc versions may order the
		# blob differently for the same tree.
		if ! diff -q <(normalize "$OUT/$f") <(normalize "$ROOT/stone/$f") >/dev/null; then
			echo "build-carrier-bsp: differs: stone/${f#./}" >&2
			failed=1
		fi
	done < <(cd "$OUT" && find . -type f | sort)
	[ "$failed" -eq 0 ] || die "stone/ is out of date; run scripts/build-carrier-bsp.sh and commit the result"
	info "stone/ matches upstream.env"
	exit 0
fi

rm -rf "$ROOT/stone"
cp -R "$OUT" "$ROOT/stone"
info "wrote stone/ from Avocado $AVOCADO_RELEASE/$AVOCADO_CHANNEL snapshot $AVOCADO_SNAPSHOT and ARK ${ARK_COMMIT:0:7}"
